
int information_append (

                                    char *       that_message,

                           struct   gopi_about   gop_about

                       ) {

//|=====================================================================================================================================================================================================================================================================================================================|
/*|*/   char buffer_message [ 32 ];                                                                                                                                                                                                                                                                                   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (  strcmp ( gop_about.system.name,   "" )  == 0  ) {  strcat ( that_message, "Name             : " );  strcat ( that_message, gop_about.system.name   );                                                                                                                 strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (  strcmp ( gop_about.system.system, "" )  == 0  ) {  strcat ( that_message, "System           : " );  strcat ( that_message, gop_about.system.system );                                                                                                                 strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (  strcmp ( gop_about.system.user,   "" )  == 0  ) {  strcat ( that_message, "User             : " );  strcat ( that_message, gop_about.system.user   );                                                                                                                 strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|                                                                                                                                                                                                                                                                              //|
/*|*/                                                            strcat ( that_message, "Time             : " );                                                      snprintf ( buffer_message, 32, "%ld",  time ( NULL )  );                                                                                        //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (           gop_about.network.number       != 0  ) {  strcat ( that_message, "IP               : " );                                                      snprintf ( buffer_message, 32, "%d",   gop_about.network.number );                                                                              //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n");     //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/       int i, ii ;                                                                                                                                                                                                                                                                                               //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/       for (   i  = 1;   i  <=               gop_about.network.number;             i  ++      )   {                                                                                                                                                                                                              //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/       for (   ii = 1;   ii <= 16 - strlen ( gop_about.network.ip [ i ] [ 1 ] );   ii ++      )   {                                                                                                                                                                                                              //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   //  name  :  address                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/           strcat ( that_message, " " );}                                                                                                                                                                                                                                                                        //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/           strcat ( that_message, gop_about.network.ip [ i ] [ 1 ] );                                                                                                                                                                                                                                            //|
/*|*/           strcat ( that_message, " : ");                                                                                                                                                                                                                                                                        //|
/*|*/           strcat ( that_message, gop_about.network.ip [ i ] [ 2 ] );                                                                                                                                                                                                                                            //|
/*|*/           strcat ( that_message, "\n" );}                                                                                                                                                                                                                                                                       //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.cpu.cores             >  0  ) {  strcat ( that_message, "CPU cores        : " );                                                      snprintf (  buffer_message,  32,  "%d",   gop_about.cpu.cores  );                                                                               //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.cpu.frequency         >  0  ) {  strcat ( that_message, "CPU frequency    : " );                                                      snprintf (  buffer_message,  32,  "%d",   gop_about.cpu.frequency  );                                                                           //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.cpu.temperature       >  0  ) {  strcat ( that_message, "CPU temperature  : " );                                                      snprintf (  buffer_message,  32,  "%d",   gop_about.cpu.temperature  );                                                                         //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.cpu.rate              >  0  ) {  strcat ( that_message, "CPU rate         : " );                                                      snprintf (  buffer_message,  32,  "%d",   gop_about.cpu.rate  );                                                                                //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "%"  );    //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.memory.total          >  0  ) {  strcat ( that_message, "Memory total     : " );                                                      snprintf (  buffer_message,  32,  "%lu",                gop_about.memory.total );                                                               //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.memory.free           >  0  ) {  strcat ( that_message, "Memory used rate : " );                                                      snprintf (  buffer_message,  32,  "%lu",  100 - ( 100 * gop_about.memory.free ) / gop_about.memory.total  );                                    //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "%"  );    //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.disk.size             >  0  ) {  strcat ( that_message, "Disk size        : " );                                                      snprintf (  buffer_message,  32,  "%lu",                gop_about.disk.size  );                                                                 //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.disk.available        >  0  ) {  strcat ( that_message, "Disk user rate   : " );                                                      snprintf (  buffer_message,  32,  "%lu",  100 - ( 100 * gop_aboutdisk.available ) / gop_about.disk.size  );                                     //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "%"  );    //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.sound.number_control  >  0  ) {  strcat ( that_message, "Sound control    : " );                                                      snprintf (  buffer_message,  32,  "%d",                 gop_about.sound.number_control  );                                                      //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.sound.number_capture  >  0  ) {  strcat ( that_message, "Sound capture    : " );                                                      snprintf (  buffer_message,  32,  "%d",                 gop_about.sound.number_capture  );                                                      //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (          gop_about.sound.number_playback >  0  ) {  strcat ( that_message, "Sound playback   : " );                                                      snprintf (  buffer_message,  32,  "%d",                 gop_about.sound.number_playback  );                                                     //|
/*|*/                                                                                                             strcat ( that_message, buffer_message );                                                                                                                          strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                               strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/                                                            strcat ( that_message, "Status           : " );                                                                                                                                                                                                      //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
/*|*/   if (  gop_about.flag.dog        ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }  strcat ( that_message, " " );                                                                                                                                                                  //|
/*|*/   if (  gop_about.flag.connectted ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }  strcat ( that_message, " " );                                                                                                                                                                  //|
/*|*/   if (  gop_about.flag.connector  ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }  strcat ( that_message, " " );                                                                                                                                                                  //|
/*|*/   if (  gop_about.flag.sound      ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }  strcat ( that_message, " " );                                                                                                                                strcat ( that_message, "\n" );    //|
/*|*/   if (  gop_about.flag.deamon     ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                 //|
//|=====================================================================================================================================================================================================================================================================================================================|

        return 1;}
