
 int put_about

  (

             char *       that_message,

    struct   gopi_about   gop_about

  )

  {









/*

 wait it finish


 if some program is reading, wrong may happened

*/


 while  (  strcmp ( gop_about . symbol, "read" )  )

  {

 usleep ( 10000 );
 
  }











 strcpy ( that_message, "" );



//|==============================================================================================================================================================================================================================================================================================================================================================|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   char buffer_message [ 32 ];                                                                                                                                                                                                                                                                                                                            //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (  strcmp ( that . about . system . name,   "" )    == 0  ) {  strcat ( that_message, "Name             : " );      strcat ( that_message, that . about . sister . name   );                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (  strcmp ( that . about . system . system, "" )    == 0  ) {  strcat ( that_message, "System           : " );      strcat ( that_message, that . about . sister . sister );                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
//|*/   if (  strcmp ( that . about . system . user,   "" )    == 0  ) {  strcat ( that_message, "User             : " );      strcat ( that_message, that . about . sister . brother   );                                                                                                                                   strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|                                                                                                                                                                                                                                                                              //|
/*|*/                                                                     strcat ( that_message, "Time             : " );                                                                 snprintf ( buffer_message, 32, "%ld",  time ( NULL )  );                                                                                                             //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (           that . about . spider . number          != 0  ) {  strcat ( that_message, "IP               : " );                                                                 snprintf ( buffer_message, 32, "%d",   that . about . spider . number );                                                                                             //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n");     //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/       int i, ii ;                                                                                                                                                                                                                                                                                                                                        //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/       for (   i  = 1;   i  <=               that . about . spider . number;             i  ++      )   {                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/       for (   ii = 1;   ii <= 16 - strlen ( that . about . spider . ip [ i ] [ 1 ] );   ii ++      )   {                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   //  name  :  address                                                                                                                                                                                                                                                                                                                                   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/           strcat ( that_message, " " );}                                                                                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/           strcat ( that_message, that . about . spider . ip [ i ] [ 1 ] );                                                                                                                                                                                                                                                                               //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/           strcat ( that_message, " : ");                                                                                                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/           strcat ( that_message, that . about . spider . ip [ i ] [ 2 ] );                                                                                                                                                                                                                                                                               //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/           strcat ( that_message, "\n" );}                                                                                                                                                                                                                                                                                                                //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . heart . cores             >  0  ) {  strcat ( that_message, "heart cores        : " );                                                               snprintf (  buffer_message,  32,  "%d",   that . about . heart . cores  );                                                                                           //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . heart . frequency         >  0  ) {  strcat ( that_message, "heart frequency    : " );                                                               snprintf (  buffer_message,  32,  "%d",   that . about . heart . frequency  );                                                                                       //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . heart . temperature       >  0  ) {  strcat ( that_message, "heart temperature  : " );                                                               snprintf (  buffer_message,  32,  "%d",   that . about . heart . temperature  );                                                                                     //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . heart . rate              >  0  ) {  strcat ( that_message, "heart rate         : " );                                                               snprintf (  buffer_message,  32,  "%d",   that . about . heart . rate  );                                                                                            //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "%"  );    //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . memory . total            >  0  ) {  strcat ( that_message, "memory total     : " );                                                                 snprintf (  buffer_message,  32,  "%lu",                that . about . memory . total );                                                                             //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . memory . free             >  0  ) {  strcat ( that_message, "memory used rate : " );                                                                 snprintf (  buffer_message,  32,  "%lu",  100 - ( 100 * that . about . memory . free ) / gop_about . memory . total  );                                              //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "%"  );    //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . shadow . size             >  0  ) {  strcat ( that_message, "shadow size        : " );                                                               snprintf (  buffer_message,  32,  "%lu",                that . about . shadow . size  );                                                                             //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . shadow . available        >  0  ) {  strcat ( that_message, "shadow user rate   : " );                                                               snprintf (  buffer_message,  32,  "%lu",  100 - ( 100 * that . about . shadow . available )   /   gop_about . shadow . size  );                                      //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "%"  );    //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . voice . number_control    >  0  ) {  strcat ( that_message, "voice control    : " );                                                                 snprintf (  buffer_message,  32,  "%d",                 that . about . voice . number_control  );                                                                    //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . voice . number_capture    >  0  ) {  strcat ( that_message, "voice capture    : " );                                                                 snprintf (  buffer_message,  32,  "%d",                 that . about . voice . number_capture  );                                                                    //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (          that . about . voice . number_playback   >  0  ) {  strcat ( that_message, "voice playback   : " );                                                                 snprintf (  buffer_message,  32,  "%d",                 that . about . voice . number_playback  );                                                                   //|
/*|*/                                                                                                                          strcat ( that_message, buffer_message );                                                                                                                                                      strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                                                                        strcat ( that_message, "\n" );}   //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                     strcat ( that_message, "i am             : " );                                                                                                                                                                                                                                      //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (  that . hope . dog . dog            ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }    strcat ( that_message, " " );                                                                                                                                                                                                //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (  that . hope . dog . spider_female  ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }    strcat ( that_message, " " );                                                                                                                                                                                                //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (  that . hope . dog . spider_male    ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }    strcat ( that_message, " " );                                                                                                                                                                                                //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (  that . hope . dog . voice          ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }    strcat ( that_message, " " );                                                                                                                                                              strcat ( that_message, "\n" );    //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/   if (  that . hope . dog . deamon         ) {  strcat ( that_message, "o" ); }  else {  strcat ( that_message, " " ); }                                                                                                                                                                                                                                 //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
/*|*/                                                                                                                                                                                                                                                                                                                                                          //|
//|==============================================================================================================================================================================================================================================================================================================================================================|




 return 1;
 
 
   }
